### ISSUE TITLE
Stoping the kernel closes ghidra

### ISSUE THREAD

**Issue by Phylante** [GhidraJupyter/ghidra-jupyter-kotlin#2] opened 2020-12-19 08:34 UTC
Titles says it all.
To reproduce : 
- Click the kotlin Notebook icon.
- Open `jupyter notebook`
- Connect by creating a new Notebook with `Ghidra(Kotlin)` in jupyter.
- Go to File > Close and Halt  
This makes ghidra close. Application log only have : `INFO  (NotebookThread) /home/user/.local/share/jupyter/runtime/kernel-62196457-6595-497f-abe8-1573925a9f68.json` nothing else.
Else I cannot stress how much this package is handy ! Thank you

**Comment by fmagin** [comment] 2020-12-19 18:01
We ran into this ourselves while developing, but there is also never really a situation were you really need to use "Close and Halt" as far as I remember.

Why this even happens isn't quite clear, my guess is that it is intended behavior in https://github.com/Kotlin/kotlin-jupyter itself, which was originally designed as a standalone process. So terminating the process made sense when the kernel receives the shutdown signal. Support for embedding a kernel as a thread inside another application was a feature I had to implement first, so this is a bug on a library we depend on that the developers of that library probably don't care about, because this project is currently the only one that uses that library for this purpose.

I'd appreciate some feedback how annoying this issue is for people(by upvoting the initial post), because personally I rarely had any use case where I wanted to shutdown a kernel like this, and tracking down and fixing the bug is probably not that trivial. There should definitely be a way to fix this, but for now it seems like it isn't that urgent.

**Comment by tmr232** [comment] 2020-12-25 12:00
Just for future reference, this seems to be the code that kills Ghidra - https://github.com/Kotlin/kotlin-jupyter/blob/adc2418d4e408aceda8229f2ab2fd4a822e7c4e4/src/main/kotlin/org/jetbrains/kotlin/jupyter/protocol.kt#L153

**Comment by fmagin** [comment] 2020-12-26 11:41
That handler is setup at https://github.com/Kotlin/kotlin-jupyter/blob/adc2418d4e408aceda8229f2ab2fd4a822e7c4e4/src/main/kotlin/org/jetbrains/kotlin/jupyter/ikotlin.kt#L114 so we could open a PR to replace that with a dedicated `controlMessageHandler` if the kernel is used in embedded mode. Killing the thread instead of the process seems like the obvious fix, but I might be missing some nuances here. The thread itself is originally created and managed by Ghidra itself, so maybe there should instead be an option for the code that prepares the kernel for embedding (i.e. this plugin), to pass a control handler, so the kernel just calls a callback on a Shutdown Request that then uses the proper Ghidra API for shutting down a Runable.

Interrupt support also seems interesting, but I am not sure if that is somehow easier to do in an embedded or Ghidra specific scenario, given that the regular kernel explicitly doesn't support it yet.

**Comment by fmagin** [comment] 2021-03-05 15:16
This was fixed in the Kotlin kernel library itself, and the new [v1.1.1 release](https://github.com/GhidraJupyter/ghidra-jupyter-kotlin/releases/tag/v1.1.1) should be using the updated version of this library.

**Closed as completed by fmagin** 2021-03-05 15:16 UTC
